# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "get_data": "01_trial.ipynb"}

modules = ["core.py",
           "try.py"]

doc_url = "https://deven367.github.io/hello_nbdev/"

git_url = "https://github.com/deven367/hello_nbdev/tree/master/"

def custom_doc_links(name): return None
