# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_functions.ipynb (unless otherwise specified).

__all__ = ['normalize']

# Cell

def normalize(data):
    """
    The function takes an array, matrix as input and normalizes
    it between 0 and 1

    Args:
        data (ndarray): any 1-D, or 2-D numpy array

    Returns:
        (ndarray): normalized ndarray

    Example:
    >>> x = [1,2,3,4,5]
    >>> normalize(x)
    array([0.  , 0.25, 0.5 , 0.75, 1.  ])
    """
    return (data - np.min(data)) / (np.max(data) - np.min(data))