# AUTOGENERATED! DO NOT EDIT! File to edit: 01_trial.ipynb (unless otherwise specified).

__all__ = ['get_data']

# Cell
def get_data(fname):
    '''
    This function gets all the text from the .txt file
    '''
    with open(fname, 'r') as f:
        all = f.read()
    return all