# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/clean_plot/",
        "doc_host": "https://deven367.github.io",
        "git_url": "https://github.com/deven367/clean_plot/",
        "lib_path": "clean_plot",
    },
    "syms": {
        "clean_plot.errors": {
            "clean_plot.errors.MyException": (
                "errors.html#myexception",
                "clean_plot/errors.py",
            ),
            "clean_plot.errors.MyException.__init__": (
                "errors.html#myexception.__init__",
                "clean_plot/errors.py",
            ),
            "clean_plot.errors.MyException.__str__": (
                "errors.html#myexception.__str__",
                "clean_plot/errors.py",
            ),
        },
        "clean_plot.heatmaps_novels": {
            "clean_plot.heatmaps_novels.corr_heatmaps": (
                "heatmaps_novels.html#corr_heatmaps",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.corr_ts": (
                "heatmaps_novels.html#corr_ts",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.heatmap_from_pkl": (
                "heatmaps_novels.html#heatmap_from_pkl",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.lex_ts": (
                "heatmaps_novels.html#lex_ts",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.plot_histograms": (
                "heatmaps_novels.html#plot_histograms",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.plot_novels": (
                "heatmaps_novels.html#plot_novels",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.plot_standardized": (
                "heatmaps_novels.html#plot_standardized",
                "clean_plot/heatmaps_novels.py",
            ),
            "clean_plot.heatmaps_novels.ssms_from_pkl": (
                "heatmaps_novels.html#ssms_from_pkl",
                "clean_plot/heatmaps_novels.py",
            ),
        },
        "clean_plot.lexical": {
            "clean_plot.lexical.interpolate": (
                "lexical.html#interpolate",
                "clean_plot/lexical.py",
            ),
            "clean_plot.lexical.load_dictionary": (
                "lexical.html#load_dictionary",
                "clean_plot/lexical.py",
            ),
            "clean_plot.lexical.load_pmi": (
                "lexical.html#load_pmi",
                "clean_plot/lexical.py",
            ),
            "clean_plot.lexical.process_v2": (
                "lexical.html#process_v2",
                "clean_plot/lexical.py",
            ),
            "clean_plot.lexical.write_to_file_lexical": (
                "lexical.html#write_to_file_lexical",
                "clean_plot/lexical.py",
            ),
        },
        "clean_plot.pickle": {
            "clean_plot.pickle.cos_sim": (
                "pickle.html#cos_sim",
                "clean_plot/pickle.py",
            ),
            "clean_plot.pickle.create_dict_whole_book": (
                "pickle.html#create_dict_whole_book",
                "clean_plot/pickle.py",
            ),
            "clean_plot.pickle.create_label": (
                "pickle.html#create_label",
                "clean_plot/pickle.py",
            ),
            "clean_plot.pickle.create_label_whole_book": (
                "pickle.html#create_label_whole_book",
                "clean_plot/pickle.py",
            ),
            "clean_plot.pickle.get_embed_method_and_name": (
                "pickle.html#get_embed_method_and_name",
                "clean_plot/pickle.py",
            ),
            "clean_plot.pickle.label": ("pickle.html#label", "clean_plot/pickle.py"),
            "clean_plot.pickle.successive_similarities": (
                "pickle.html#successive_similarities",
                "clean_plot/pickle.py",
            ),
        },
        "clean_plot.plot.utils": {
            "clean_plot.plot.utils.Plot": (
                "plot.utils.html#plot",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.__init__": (
                "plot.utils.html#plot.__init__",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.__repr__": (
                "plot.utils.html#plot.__repr__",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.create_ssms": (
                "plot.utils.html#plot.create_ssms",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.get_corr_plots": (
                "plot.utils.html#plot.get_corr_plots",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.get_normalized": (
                "plot.utils.html#plot.get_normalized",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.get_sectional_ssms": (
                "plot.utils.html#plot.get_sectional_ssms",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.get_standardized": (
                "plot.utils.html#plot.get_standardized",
                "clean_plot/plot/utils.py",
            ),
            "clean_plot.plot.utils.Plot.view_all_files": (
                "plot.utils.html#plot.view_all_files",
                "clean_plot/plot/utils.py",
            ),
        },
        "clean_plot.utils": {
            "clean_plot.utils.check_files": (
                "utils.html#check_files",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.chelp": ("utils.html#chelp", "clean_plot/utils.py"),
            "clean_plot.utils.clean": ("utils.html#clean", "clean_plot/utils.py"),
            "clean_plot.utils.download_nltk_dep": (
                "utils.html#download_nltk_dep",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.get_data": ("utils.html#get_data", "clean_plot/utils.py"),
            "clean_plot.utils.get_wordnet_pos": (
                "utils.html#get_wordnet_pos",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.load_dictionary": (
                "utils.html#load_dictionary",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.load_pmi": ("utils.html#load_pmi", "clean_plot/utils.py"),
            "clean_plot.utils.loader": ("utils.html#loader", "clean_plot/utils.py"),
            "clean_plot.utils.make_sentences": (
                "utils.html#make_sentences",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.normalize": (
                "utils.html#normalize",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.num_words": (
                "utils.html#num_words",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.process_for_lexical": (
                "utils.html#process_for_lexical",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.remove_punc_clean": (
                "utils.html#remove_punc_clean",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.remove_punctuations": (
                "utils.html#remove_punctuations",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.remove_stopwords": (
                "utils.html#remove_stopwords",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.rm_useless_spaces": (
                "utils.html#rm_useless_spaces",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.split_by_newline": (
                "utils.html#split_by_newline",
                "clean_plot/utils.py",
            ),
            "clean_plot.utils.write_to_file_cleaned": (
                "utils.html#write_to_file_cleaned",
                "clean_plot/utils.py",
            ),
        },
    },
}
