# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "get_data": "01_trial.ipynb",
         "get_features": "02_feature_extractor.ipynb",
         "normalize": "03_functions.ipynb",
         "split_by_newline": "03_functions.ipynb",
         "rm_useless_spaces": "03_functions.ipynb",
         "make_sentences": "03_functions.ipynb",
         "write_to_file_cleaned": "03_functions.ipynb",
         "clean": "03_functions.ipynb",
         "get_wordnet_pos": "03_functions.ipynb",
         "remove_stopwords": "03_functions.ipynb",
         "remove_punctuations": "03_functions.ipynb",
         "remove_punc_clean": "03_functions.ipynb",
         "process": "03_functions.ipynb",
         "label": "04_pickle.ipynb",
         "cos_sim": "04_pickle.ipynb"}

modules = ["core.py",
           "trial.py",
           "feature_extractor.py",
           "functions.py",
           "pickle.py"]

doc_url = "https://deven367.github.io/clean_plot/"

git_url = "https://github.com/deven367/clean_plot/tree/master/"

def custom_doc_links(name): return None
