# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "get_data": "01_trial.ipynb",
         "get_features": "02_feature_extractor.ipynb",
         "normalize": "03_functions.ipynb",
         "split_by_newline": "03_functions.ipynb",
         "make_sentences": "03_functions.ipynb"}

modules = ["core.py",
           "trial.py",
           "feature_extractor.py",
           "functions.py"]

doc_url = "https://deven367.github.io/clean_plot/"

git_url = "https://github.com/deven367/clean_plot/tree/master/"

def custom_doc_links(name): return None
