# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_data', 'load_pmi', 'load_dictionary', 'say_hello', 'HelloSayer']

# Cell
import pickle
import numpy as np

# Cell
def get_data(fname):
    '''
    This function gets all the text from the .txt file
    '''
    with open(fname, 'r') as f:
        all_text = f.read()
    return all_text

# Cell
def load_pmi(fname):
    pmi = np.load(fname)
    print('Loaded {}'.format(fname))
    return pmi


# Cell
def load_dictionary(fname):
    """
    Given a fname, function loads a `pkl` dictionary
    from the current directory

    Args:
        fname ([str]): Enter the filename

    Returns:
        [dict]: Returns the loaded pkl file as a
                dict
    """
    fname = open(fname, 'rb')
    data = pickle.load(fname)
    return data

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        return say_hello(self.to)