"""Implementations of custom errors"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_errors.ipynb.

# %% auto #0
__all__ = ['MyException']

# %% ../nbs/07_errors.ipynb #e47f666a
class MyException(Exception):
    def __init__(self, message):
        super().__init__(message)

        self.message = message

    def __str__(self):
        return self.message


# %% ../nbs/07_errors.ipynb #bd0b5135
import inspect
