# AUTOGENERATED! DO NOT EDIT! File to edit: 03_functions.ipynb (unless otherwise specified).

__all__ = ['normalize', 'split_by_newline', 'make_sentences']

# Cell
def normalize(data):
    """
    The function takes an array, matrix as input and normalizes
    it between 0 and 1

    Args:
        data (ndarray): any 1-D, or 2-D numpy array

    Returns:
        (ndarray): normalized ndarray
    """
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Cell
def split_by_newline(all):
    """
    Only use when sentences are already tokenized
    returns sentences split by '\\n' if len(line) > 0

    Args:
        all (str): tokenized string to be split by '\\n'

    Returns:
        list: list of sentences split by '\\n'
    """
    return [line.lower() for line in all.split('\n') if len(line) > 0]

# Cell
def make_sentences(all):
    all_cleaned = all.replace('\n',' ')
    sentences = sent_tokenize(all_cleaned)
    return sentences