# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_heatmaps_novels.ipynb (unless otherwise specified).

__all__ = ['plot_novels']

# Cell
from .core import loader
from .pickle import label
from .functions import normalize
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from fastcore.all import *
from pathlib import Path

# Cell
@call_parse
def plot_novels(path: Param("path for embeddings"),
                start: Param("start for section", default=0, type=int),
                end: Param("end for section", default=-1, type=int)):
    "Generates plots for embeddings in the folder"

    files = loader(path, '.npy')
    curr = Path.cwd()
    if start > 0:
        new_path = curr/f'sections_{start} {end}'
        new_path.mkdir(exist_ok=True)
    else:
        new_path = curr/'full_plots'
        new_path.mkdir(exist_ok=True)

    for f in files:
        fname = f.stem.split('_cleaned_')
        book, method = fname[0], label(fname[1])
        title = f'{book.title()} {method}'

        em = np.load(f)
        sim = cosine_similarity(em, em)
        n = normalize(sim)
        sns.heatmap(n[start:end, start:end], cmap='hot',
                    vmin=0, vmax=1, square=True,
                    xticklabels=20, yticklabels=20)

        plt.yticks(rotation = 0)
        plt.title(title)

        plt.savefig(new_path/f'{title}.png', dpi = 300, bbox_inches='tight')
        plt.clf()
        del em, sim, n