# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_pickle.ipynb (unless otherwise specified).

__all__ = ['label', 'cos_sim']

# Cell
import os
import numpy as np
import pickle
import string
from numpy import dot
from numpy.linalg import norm

# Cell
def label(arg):
    """
    Returns the full name of the model based on the abbreviation
    """
    switcher = {
        'dcltr_base': "DeCLUTR Base",
        'dcltr_sm': "DeCLUTR Small",
        'distil': "DistilBERT",
        'if_FT': "InferSent FastText",
        'if_glove': "InferSent GloVe",
        'roberta': "RoBERTa",
        'use': "USE",
        'new_lex': 'Lexical Vectors',
        'old_lex': 'Lexical Weights',
        'lexical_wt': 'Lexical Weights',
        'lex_vect': 'Lexical Vectors',
        'lex_vect_corr_ts': 'Lexical Vectors (Corr)'
    }
    return switcher.get(arg)

# Cell
def cos_sim(a, b):
    """
    Returns the cosine similarity between 2 vectors.
    """
    return dot(a, b)/(norm(a)*norm(b))