# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_plot.ipynb (unless otherwise specified).

__all__ = ['Plot']

# Cell
from fastcore.basics import store_attr
from fastcore.xtras import globtastic
from fastcore.meta import delegates

# Cell
#hide
import inspect

# Cell
class Plot:
    def __init__(self, path):
        store_attr()

    @delegates(globtastic)
    def view_all_files(self, **kwargs):
        return globtastic(self.path, **kwargs)

    def create_ssms(self):
        pass

    def get_normalized(self):
        pass

    def get_standardized(self):
        pass

    def get_corr_plots(self):
        pass